# Generated by Django 5.2 on 2025-05-01 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('bio', models.TextField(db_column='bio', null=True)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('imageUrl', models.CharField(db_column='image_url', max_length=255, null=True)),
                ('gender', models.CharField(db_column='gender', max_length=255)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
    ]
