# Generated by Django 5.2 on 2025-05-04 10:37

import spotifyBE.artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='artists',
            name='image_file',
            field=models.ImageField(db_column='image_url', null=True, upload_to=spotifyBE.artists.models.image_upload_path),
        ),
    ]
