# Generated by Django 5.2 on 2025-05-06 07:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artists_imageurl_artists_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='image_url', max_length=255, null=True, verbose_name='image'),
        ),
    ]
