# Generated by Django 5.2 on 2025-04-23 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('duration', models.IntegerField(db_column='duration')),
                ('urlTrack', models.CharField(db_column='url_track', max_length=255)),
                ('urlVideo', models.CharField(db_column='url_video', max_length=255, null=True)),
                ('releaseDate', models.DateField(db_column='release_date', null=True)),
                ('imageUrl', models.CharField(db_column='image_url', max_length=255, null=True)),
                ('lyrics', models.TextField(db_column='lyrics', null=True)),
                ('playCount', models.IntegerField(db_column='play_count')),
                ('createdAt', models.DateTimeField(db_column='created_at')),
                ('status', models.CharField(db_column='status', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
    ]
