# Generated by Django 5.2 on 2025-05-02 02:31

import spotifyBE.tracks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='urlVideo',
        ),
        migrations.AddField(
            model_name='tracks',
            name='image_file',
            field=models.ImageField(db_column='image_url', null=True, upload_to=spotifyBE.tracks.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='tracks',
            name='video_file',
            field=models.FileField(db_column='url_video', null=True, upload_to=spotifyBE.tracks.models.video_upload_path),
        ),
    ]
