# Generated by Django 5.2 on 2025-05-05 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_tracks_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_file',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='url_track', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='url_video', max_length=255, null=True),
        ),
    ]
