# Generated by Django 5.2 on 2025-04-15 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('createdAt', models.DateField(db_column='created_at')),
                ('status', models.CharField(db_column='status', max_length=255)),
                ('users', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='users.users')),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
    ]
