# Generated by Django 5.2 on 2025-05-01 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('createdAt', models.DateField(auto_now_add=True, db_column='created_at')),
                ('status', models.CharField(db_column='status', max_length=255)),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
    ]
