# Generated by Django 5.2 on 2025-04-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='createdAt',
            field=models.DateField(auto_now_add=True, db_column='created_at'),
        ),
    ]
