# Generated by Django 5.2 on 2025-05-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlists_updatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlists',
            old_name='users',
            new_name='user',
        ),
    ]
