# Generated by Django 5.2 on 2025-05-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0004_alter_tracks_track_file_alter_tracks_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentTime', models.IntegerField(db_column='current_time', default=0)),
                ('is_repeat', models.BooleanField(default=False)),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, related_name='playbars', to='tracks.tracks')),
            ],
            options={
                'db_table': 'playbar',
            },
        ),
    ]
