# Generated by Django 5.2 on 2025-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=255, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('imageUrl', models.CharField(blank=True, db_column='image_url', max_length=255, null=True)),
                ('birthDay', models.DateField(blank=True, db_column='birth_day', null=True)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('status', models.CharField(db_column='status', default='active', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
