# Generated by Django 5.2 on 2025-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birthDay',
            field=models.DateField(blank=True, db_column='birth_day', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(db_column='email', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, db_column='gender', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='imageUrl',
            field=models.CharField(blank=True, db_column='image_url', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(db_column='status', default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_column='username', max_length=255, unique=True),
        ),
    ]
