# Generated by Django 5.2 on 2025-05-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbar', '0001_initial'),
        ('users', '0002_alter_users_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='playbar',
            field=models.OneToOneField(db_column='playbar_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='playbar.playbar'),
        ),
    ]
