# Generated by Django 5.2 on 2025-04-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('playlists', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTracks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trackNumber', models.IntegerField(db_column='track_number')),
                ('album', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.albums')),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tracks.tracks')),
            ],
            options={
                'db_table': 'album_tracks',
            },
        ),
        migrations.CreateModel(
            name='ArtistTracks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.BooleanField(db_column='owner')),
                ('artist', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artists')),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='tracks.tracks')),
            ],
            options={
                'db_table': 'artist_tracks',
            },
        ),
        migrations.CreateModel(
            name='PlaylistTracks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trackNumber', models.IntegerField(db_column='track_number')),
                ('addedAt', models.DateTimeField(db_column='added_at')),
                ('playlist', models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='playlists.playlists')),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='tracks.tracks')),
            ],
            options={
                'db_table': 'playlist_tracks',
            },
        ),
    ]
