# Generated by Django 5.2 on 2025-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttracks',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='added_at'),
        ),
    ]
