# Generated by Django 5.2 on 2025-05-01 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('releaseDate', models.DateField(db_column='release_date', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('imageUrl', models.CharField(db_column='image_url', max_length=255, null=True)),
                ('artist', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artists')),
            ],
            options={
                'db_table': 'albums',
            },
        ),
    ]
