# Generated by Django 5.2 on 2025-05-06 08:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='imageUrl',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='image_url', max_length=255, null=True, verbose_name='image'),
        ),
    ]
